Hyperbolic functions
szymon-zygula/cusymint pull request #6
Opened 2022-09-06 13:08 UTC by zh-qs

2022-09-08 16:42 UTC, TortillaZHawaii requested changes
Drobny bug z potęgami. Szczegóły w komentarzach.
I dla spójności z resztą nazwy commitów z wielkiej litery.

2022-09-08 16:42 UTC, TortillaZHawaii commented on engine/src/Symbol/Symbol.cuh
> +#include "Symbol/Hyperbolic.cuh"
Czemu jest tutaj ten include?

2022-09-08 16:42 UTC, TortillaZHawaii commented on engine/src/Symbol/Hyperbolic.cu
> +        return Sym::num(0.5)*(Sym::e()^arg - Sym::e()^(-arg));
Jest problem z potęgami bo mają one niższy priorytet niż się można spodziewać w cpp (w cpp służą domyślnie do operacji bitowych nie potęgowania jak w matmie) przez co `Sym::integral(Sym::sinh(Sym::var()))` jest interpretowane jako `∫(0.500000*((e^(x-e))^-x))dx`, co później z jakiegoś powodu wykrzacza cały program. Ogólnie to też warto dodać (póki nie dodałem frameworku do testów), przykładowe całki do `main.cu` w `create_test_integrals()`.

2022-09-08 16:42 UTC, TortillaZHawaii commented on engine/src/Symbol/Hyperbolic.cu
> +        return Sym::num(0.5)*(Sym::e()^arg - Sym::e()^(-arg));
Jak zmieniłem na `Sym::num(0.5)*((Sym::e()^arg) - (Sym::e()^(-arg)))` wszystko jest okej: `∫(0.500000*((e^x)-(e^-x)))dx`.

2022-09-09 09:35 UTC, zh-qs commented on engine/src/Symbol/Hyperbolic.cu
> +        return Sym::num(0.5)*(Sym::e()^arg - Sym::e()^(-arg));
Faktycznie, dzięki za uwagę, poprawiłem

2022-09-09 09:37 UTC, zh-qs commented on engine/src/Symbol/Symbol.cuh
> +#include "Symbol/Hyperbolic.cuh"
Dla wygody i spójności, żeby np. w main.cu nie trzeba było dodawać tego include'a; wszystkie funkcje dotyczące symboli mogą być dostępne includując tylko Symbol.cuh

2022-09-09 12:29 UTC, TortillaZHawaii approved these changes
LGTM

2022-09-09 12:30 UTC, merged